### ISSUE TITLE
Invalid value for transfer: smpte-st-2084

### ISSUE THREAD

**Issue by DrSky2007** [yllanos/corozo#7]
The parameter "transfer=smpte-st-2084" is deprecated, now it is "transfer=smpte2084"

**Comment by yllanos** [comment]
You get this as a warning, correct? Can you share what ffmpeg version are you using? 

Thanks

**Comment by DrSky2007** [comment]
Yes, it's a warning:
`[libx265 @ 0x558d9a10bb00] Invalid value for transfer: smpte-st-2084.`
`x265 [info]: HEVC encoder version 3.2.1+1-b5c86a64bbbe`
`x265 [info]: build info [Linux][GCC 9.2.1][64 bit] 10bit`
`x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2`
`x265 [error]: Recommended Settings for HDR: colour primaries should be BT.2020,`
`                                            transfer characteristics should be SMPTE ST.2084,`
`                                            matrix coeffs should be BT.2020,`
`                                            the input video should be 10 bit 4:2:0`
`                                            Disabling offset tuning for HDR videos`

ffmpeg is from the debian testing repositories:
`ffmpeg version 4.2.2-1+b1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Debian 9.2.1-28)`

There is no warning anymore, if I use `transfer=smpte2084` instead of `transfer=smpte-st-2084`.

**Comment by yllanos** [comment]
OK your ffmpeg is 4.x and yes, if you change the instruction as mentioned the warning will go away. But the script is designed for ffmpeg 3.x which is incompatible with transfer=smpte2084 unfortunately.

I will update the script for ffmpeg version 4.x and leave e.x version as legacy.

Thanks

**Comment by marcelloinfoweb** [comment]
Do you have an update for ffmpeg version 4?

**Comment by yllanos** [comment]
Hi. Yes.

I have updated the project with support for ffmpeg 4.x (commit a96ed79)

I'm closing this issue. 

Thanks
